version: "3.8"

services:
  airflow:
    image: apache/airflow:2.8.1
    container_name: airflow_AF
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock   # 🔥 clé DockerOperator
    command: >
      bash -c "
      airflow db init &&
      airflow users create
        --username user
        --password user123
        --firstname Adam
        --lastname adam
        --role Admin
        --email admin@mlops.local &&
      airflow webserver & airflow scheduler
      "
