apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlops-ingress
spec:
  rules:
    - host: mlops.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: streamlit-ui
                port:
                  number: 8501
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8000
