apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops

resources:
  - namespace.yaml
  - gateway.yaml
  - predict-text-api.yaml
  - predict-image-api.yaml
  - training-api.yaml
  - streamlit-ui.yaml
  - ingress.yaml
